parameters:
    #TODO: make parameters configurable

    symfony_cmf_content.document: Symfony\Cmf\Bundle\ContentBundle\Document\StaticContent
    symfony_cmf_content.static_basepath: /cms/content/static

