parameters:
    #TODO: make parameters configurable

    symfony.cmf.content.document: Symfony\Cmf\Bundle\ContentBundle\Document\StaticContent
    symfony.cmf.content.static_basepath: /cms/content/static

