services:
    symfony.cmf.content.controller:
        class: Symfony\Cmf\Bundle\ContentBundle\Controller\ContentController
        arguments:
            container: "@service_container"
        shared: true
